"""Parseur RGBDS minimal utilisé par les générateurs (pas de ROM requise)."""

import pytest

from pokeblue.knowledge.pokered.asm import (
    AsmConstants,
    AsmError,
    constant_name,
    macro_args,
    parse_sym,
    strip_comment,
)


def _load(tmp_path, text):
    path = tmp_path / "constants.asm"
    path.write_text(text, encoding="utf-8")
    consts = AsmConstants()
    return consts, consts.load(path)


def test_strip_comment_ignores_semicolon_in_string():
    assert strip_comment('db "a;b" ; commentaire') == 'db "a;b"'
    assert strip_comment("   ; seulement un commentaire") == ""


def test_macro_args():
    assert macro_args("db WATER,  FIRE, SUPER_EFFECTIVE", "db") == ["WATER", "FIRE", "SUPER_EFFECTIVE"]
    assert macro_args("rsreset", "rsreset") == []
    assert macro_args("dw Foo", "db") is None


def test_const_enumeration(tmp_path):
    consts, names = _load(tmp_path, """
        const_def
        const ZERO        ; $00
        const_skip 2
        const THREE
        const_next $14
        const TWENTY
        DEF COUNT EQU const_value
        const_def 1, 2
        const ONE
        const THREE_BIS
        const_def 3
        shift_const BIT3
    """)
    assert names == ["ZERO", "THREE", "TWENTY", "ONE", "THREE_BIS", "BIT3"]
    assert consts.require("ZERO", "THREE", "TWENTY", "COUNT", "ONE", "THREE_BIS", "BIT3") == {
        "ZERO": 0, "THREE": 3, "TWENTY": 0x14, "COUNT": 0x15, "ONE": 1, "THREE_BIS": 3, "BIT3": 8,
    }


def test_struct_offsets(tmp_path):
    consts, _ = _load(tmp_path, """
        DEF N EQU 4
        rsreset
        DEF S_SPECIES rb
        DEF S_HP      rw
        DEF S_MOVES   rb N
        rsset S_HP
        DEF S_HP_HI   rb
                      rb_skip
        DEF S_AFTER   rb
        DEF S_LEN EQU _RS
    """)
    assert consts.require("S_SPECIES", "S_HP", "S_MOVES", "S_HP_HI", "S_AFTER", "S_LEN") == {
        "S_SPECIES": 0, "S_HP": 1, "S_MOVES": 3, "S_HP_HI": 1, "S_AFTER": 3, "S_LEN": 4,
    }


def test_number_formats_and_operators(tmp_path):
    consts, _ = _load(tmp_path, """
        DEF HEX  EQU $1A
        DEF BIN  EQU %00111111
        DEF DEC  EQU 05
        DEF EXPR EQU (HEX + 7) / 8 * 2
        DEF MOD  EQU 7 %3
        DEF NEG  EQU -1
        DEF TRUNC EQU -7 / 2
    """)
    assert consts.require("HEX", "BIN", "DEC", "EXPR", "MOD", "NEG", "TRUNC") == {
        "HEX": 26, "BIN": 63, "DEC": 5, "EXPR": 8, "MOD": 1, "NEG": -1, "TRUNC": -3,
    }


@pytest.mark.parametrize(("expr", "expected"), [
    # Priorités rgbasm(5) : `<<` et `& | ^` passent avant `+ -` (contrairement à Python).
    ("1 << 4 + 1", 17),
    ("2 + 3 & 1", 3),
    ("1 << 4 | 63 & %11", 3),   # `& | ^` au même niveau, associatifs à gauche
    ("~0 & $FF", 255),
    ("(2 + 3) * 4", 20),
])
def test_rgbds_operator_precedence(expr, expected):
    assert AsmConstants().eval(expr) == expected


def test_map_const_and_macro_bodies(tmp_path):
    consts, names = _load(tmp_path, """
        MACRO map_const
            const \\1
        ENDM
        const_def
        map_const PALLET_TOWN, 10, 9
        map_const ROUTE_1,     10, 18
    """)
    assert names == ["PALLET_TOWN", "ROUTE_1"]
    assert consts["ROUTE_1"] == 1
    assert (consts["ROUTE_1_WIDTH"], consts["ROUTE_1_HEIGHT"]) == (10, 18)


def test_tm_hm_item_macros(tmp_path):
    consts, names = _load(tmp_path, """
        const_def
        const_next $C4
        add_hm CUT
        add_hm FLY
        add_tm MEGA_PUNCH
    """)
    assert names == ["HM_CUT", "HM_FLY", "TM_MEGA_PUNCH"]
    assert consts.require("HM_CUT", "TM_MEGA_PUNCH") == {"HM_CUT": 0xC4, "TM_MEGA_PUNCH": 0xC6}


def test_unresolved_definition_is_absent_not_wrong(tmp_path):
    consts, _ = _load(tmp_path, "DEF A EQU UNKNOWN | 1\nDEF B EQU 2\n")
    assert "A" not in consts.values
    assert consts.unresolved == {"A": "UNKNOWN | 1"}
    with pytest.raises(AsmError):
        consts.require("A")


def test_conditionals_are_rejected(tmp_path):
    with pytest.raises(AsmError):
        _load(tmp_path, "IF DEF(_RED)\nDEF X EQU 1\nENDC\n")


@pytest.mark.parametrize(("symbol", "expected"), [
    ("wEventFlags", "W_EVENT_FLAGS"),
    ("wPartyMon1HP", "W_PARTY_MON1_HP"),
    ("wPartyMon2HPExp", "W_PARTY_MON2_HP_EXP"),
    ("wBattleMonDVs", "W_BATTLE_MON_DVS"),
    ("wXCoord", "W_X_COORD"),
    ("wSpritePlayerStateData1FacingDirection", "W_SPRITE_PLAYER_STATE_DATA1_FACING_DIRECTION"),
    ("wNPCMovementDirections", "W_NPC_MOVEMENT_DIRECTIONS"),
    ("hJoy5", "H_JOY5"),
])
def test_constant_name(symbol, expected):
    assert constant_name(symbol) == expected


def test_parse_sym_skips_exported_constants(tmp_path):
    path = tmp_path / "game.sym"
    path.write_text("; File generated by rgblink\n01 SOME_CONSTANT\n00:9800 vBGMap0\n")
    assert parse_sym(path) == [(0, 0x9800, "vBGMap0")]
